[package]
name = "solvertools"
version = "0.1.0"
authors = ["Robyn Speer <rspeer@luminoso.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
grep-searcher = "*"
tempfile = "*"
grep-regex = "*"
